/**
 * Dados dos equipamentos médicos (ultrassom) baseados na planilha Excel fornecida
 * Este arquivo contém a estrutura de dados para importação no sistema
 */

export const excelEquipmentData = {
  brands: [
    { name: "SAMSUNG", isOwn: true, color: "245" },
    { name: "GE", color: "200" },
    { name: "Mindray", color: "10" },
    { name: "BARD", color: "270" },
    { name: "BD", color: "0" },
    { name: "Fujifilm", color: "120" },
    { name: "Esaote", color: "30" },
  ],

  categories: [
    { name: "Hardware", icon: "Cpu", description: "Especificações de hardware e componentes físicos", color: "0" },
    { name: "Radiologia", icon: "ScanLine", description: "Funcionalidades de radiologia", color: "200" },
    { name: "Obstetrícia", icon: "Baby", description: "Funcionalidades obstétricas", color: "300" },
    { name: "Cardiologia", icon: "HeartPulse", description: "Funcionalidades cardíacas", color: "10" },
    { name: "Vascular", icon: "Activity", description: "Funcionalidades vasculares", color: "150" },
  ],

  differentials: [
    { label: "Portátil com bateria", icon: "BatteryCharging" },
    { label: "IA integrada", icon: "Sparkles" },
    { label: "Tela touch", icon: "Touchpad" },
    { label: "Conectividade DICOM", icon: "Wifi" },
    { label: "Alta resolução", icon: "Maximize2" },
    { label: "Múltiplos transdutores", icon: "Radio" },
    { label: "Workflow otimizado", icon: "Zap" },
    { label: "Suporte 24/7", icon: "ShieldCheck" },
  ],

  fields: [
    // Hardware
    { key: "price", label: "Média de preço", type: "text", unit: "BRL", group: "Hardware", highlight: true, order: 0 },
    { key: "channels", label: "Canais", type: "number", group: "Hardware", highlight: true, order: 1 },
    { key: "os", label: "Sistema operacional", type: "text", group: "Hardware", order: 2 },
    { key: "wifi", label: "Wi-Fi", type: "boolean", group: "Hardware", order: 3 },
    { key: "monitorType", label: "Tipo de Monitor", type: "text", group: "Hardware", order: 4 },
    { key: "monitorSize", label: "Tamanho do Monitor", type: "number", unit: "pol", group: "Hardware", order: 5 },
    { key: "touchScreen", label: "Tela Touch", type: "boolean", group: "Hardware", order: 6 },
    { key: "storage", label: "Armazenamento", type: "text", group: "Hardware", order: 7 },
    { key: "activePorts", label: "Portas Ativas", type: "number", group: "Hardware", order: 8 },
    { key: "usbPorts", label: "Portas USB", type: "number", group: "Hardware", order: 9 },
    { key: "weight", label: "Peso", type: "number", unit: "kg", group: "Hardware", order: 10 },
    { key: "dimensions", label: "Dimensões (AxLxP)", type: "text", group: "Hardware", order: 11 },
    { key: "heightAdjust", label: "Ajuste de altura", type: "boolean", group: "Hardware", order: 12 },
    { key: "articulatedArm", label: "Braço articulado", type: "boolean", group: "Hardware", order: 13 },
    { key: "gelWarmer", label: "Aquecedor de gel", type: "boolean", group: "Hardware", order: 14 },
    { key: "pedalOption", label: "Possibilidade de Pedal", type: "boolean", group: "Hardware", order: 15 },
    { key: "keyboardType", label: "Tipo de teclado", type: "select", options: ["Físico", "Virtual", "Híbrido"], group: "Hardware", order: 16 },
    { key: "battery", label: "Bateria", type: "boolean", group: "Hardware", order: 17 },
    { key: "transducerHolders", label: "Suporte para transdutores", type: "number", group: "Hardware", order: 18 },
    // Radiologia
    { key: "radAutoMeas", label: "Medidas automáticas", type: "boolean", group: "Radiologia", order: 19 },
    { key: "radAI", label: "Recursos de IA", type: "boolean", group: "Radiologia", highlight: true, order: 20 },
    { key: "swConvex", label: "Share Wave no Convexo", type: "boolean", group: "Radiologia", order: 21 },
    { key: "swLinear", label: "Share Wave no Linear", type: "boolean", group: "Radiologia", order: 22 },
    { key: "ceus", label: "Contraste por Microbolhas", type: "boolean", group: "Radiologia", order: 23 },
    { key: "singleCrystal", label: "Single Cristal", type: "boolean", group: "Radiologia", order: 24 },
    { key: "maxFreq", label: "Maior Frequencia", type: "number", unit: "MHz", group: "Radiologia", order: 25 },
  ],

  equipments: [
    // SAMSUNG
    {
      name: "Meerkat",
      shortName: "Meerkat",
      brandName: "SAMSUNG",
      tier: "premium",
      tagline: "Equipamento Samsung de alta performance",
      description: "Sistema de ultrassom Samsung Meerkat com tecnologia avançada",
      categories: ["Hardware", "Radiologia"],
      bestFor: ["Radiologia"],
      differentials: ["IA integrada", "Alta resolução"],
      specs: {
        price: "R$ 450k–600k",
        channels: 128,
        os: "Linux Embedded",
        wifi: true,
        monitorType: "LED Full HD",
        monitorSize: 21.5,
        touchScreen: true,
        storage: "1 TB SSD",
        activePorts: 4,
        usbPorts: 6,
        weight: 65,
        dimensions: "146 x 56 x 80 cm",
        heightAdjust: true,
        articulatedArm: true,
        gelWarmer: true,
        pedalOption: true,
        keyboardType: "Híbrido",
        battery: false,
        transducerHolders: 5,
        radAutoMeas: true,
        radAI: true,
        swConvex: true,
        swLinear: true,
        ceus: true,
        singleCrystal: true,
        maxFreq: 18,
      },
      highlights: ["Tecnologia avançada", "128 canais", "IA integrada"],
      releaseYear: 2024,
    },
    // GE
    {
      name: "Venue Go",
      shortName: "Venue Go",
      brandName: "GE",
      tier: "medium",
      tagline: "Equipamento GE portátil",
      description: "Sistema de ultrassom GE Venue Go com portabilidade",
      categories: ["Hardware", "Radiologia"],
      bestFor: ["Radiologia"],
      differentials: ["Portátil com bateria", "Conectividade DICOM"],
      specs: {
        price: "R$ 200k–300k",
        channels: 96,
        os: "Windows 10 IoT",
        wifi: true,
        monitorType: "LED HD",
        monitorSize: 15,
        touchScreen: true,
        storage: "512 GB SSD",
        activePorts: 3,
        usbPorts: 4,
        weight: 3.8,
        dimensions: "38 x 36 x 7 cm",
        heightAdjust: false,
        articulatedArm: false,
        gelWarmer: false,
        pedalOption: true,
        keyboardType: "Virtual",
        battery: true,
        transducerHolders: 3,
        radAutoMeas: true,
        radAI: false,
        swConvex: false,
        swLinear: false,
        ceus: false,
        singleCrystal: false,
        maxFreq: 12,
      },
      highlights: ["Portátil", "Bateria", "Leve"],
      releaseYear: 2023,
    },
    {
      name: "Venue Fit",
      shortName: "Venue Fit",
      brandName: "GE",
      tier: "medium",
      tagline: "Equipamento GE compacto",
      description: "Sistema de ultrassom GE Venue Fit com design compacto",
      categories: ["Hardware", "Radiologia"],
      bestFor: ["Radiologia"],
      differentials: ["Portátil com bateria", "Tela touch"],
      specs: {
        price: "R$ 180k–250k",
        channels: 80,
        os: "Windows 10 IoT",
        wifi: true,
        monitorType: "LED HD",
        monitorSize: 13,
        touchScreen: true,
        storage: "256 GB SSD",
        activePorts: 2,
        usbPorts: 3,
        weight: 2.5,
        dimensions: "35 x 32 x 5 cm",
        heightAdjust: false,
        articulatedArm: false,
        gelWarmer: false,
        pedalOption: false,
        keyboardType: "Virtual",
        battery: true,
        transducerHolders: 2,
        radAutoMeas: false,
        radAI: false,
        swConvex: false,
        swLinear: false,
        ceus: false,
        singleCrystal: false,
        maxFreq: 10,
      },
      highlights: ["Compacto", "Leve", "Portátil"],
      releaseYear: 2023,
    },
    // Mindray
    {
      name: "TE7",
      shortName: "TE7",
      brandName: "Mindray",
      tier: "premium",
      tagline: "Equipamento Mindray de topo de linha",
      description: "Sistema de ultrassom Mindray TE7 com tecnologia premium",
      categories: ["Hardware", "Radiologia", "Cardiologia"],
      bestFor: ["Cardiologia", "Radiologia"],
      differentials: ["Alta resolução", "IA integrada"],
      specs: {
        price: "R$ 500k–700k",
        channels: 192,
        os: "Linux Embedded",
        wifi: true,
        monitorType: "LED 4K",
        monitorSize: 23.8,
        touchScreen: true,
        storage: "1 TB SSD",
        activePorts: 4,
        usbPorts: 6,
        weight: 75,
        dimensions: "150 x 60 x 90 cm",
        heightAdjust: true,
        articulatedArm: true,
        gelWarmer: true,
        pedalOption: true,
        keyboardType: "Híbrido",
        battery: false,
        transducerHolders: 5,
        radAutoMeas: true,
        radAI: true,
        swConvex: true,
        swLinear: true,
        ceus: true,
        singleCrystal: true,
        maxFreq: 20,
      },
      highlights: ["192 canais", "4K", "IA integrada"],
      releaseYear: 2024,
    },
    {
      name: "TE9",
      shortName: "TE9",
      brandName: "Mindray",
      tier: "premium",
      tagline: "Equipamento Mindray premium",
      description: "Sistema de ultrassom Mindray TE9 com tecnologia avançada",
      categories: ["Hardware", "Radiologia", "Cardiologia"],
      bestFor: ["Cardiologia"],
      differentials: ["Alta resolução", "Múltiplos transdutores"],
      specs: {
        price: "R$ 550k–750k",
        channels: 256,
        os: "Linux Embedded",
        wifi: true,
        monitorType: "LED 4K",
        monitorSize: 27,
        touchScreen: true,
        storage: "2 TB SSD",
        activePorts: 4,
        usbPorts: 8,
        weight: 85,
        dimensions: "155 x 65 x 95 cm",
        heightAdjust: true,
        articulatedArm: true,
        gelWarmer: true,
        pedalOption: true,
        keyboardType: "Físico",
        battery: false,
        transducerHolders: 6,
        radAutoMeas: true,
        radAI: true,
        swConvex: true,
        swLinear: true,
        ceus: true,
        singleCrystal: true,
        maxFreq: 22,
      },
      highlights: ["256 canais", "4K", "Múltiplos transdutores"],
      releaseYear: 2024,
    },
    {
      name: "TEX20",
      shortName: "TEX20",
      brandName: "Mindray",
      tier: "premium",
      tagline: "Equipamento Mindray flagship",
      description: "Sistema de ultrassom Mindray TEX20 de topo de linha",
      categories: ["Hardware", "Radiologia", "Cardiologia", "Obstetrícia"],
      bestFor: ["Cardiologia", "Obstetrícia"],
      differentials: ["Alta resolução", "IA integrada", "Múltiplos transdutores"],
      specs: {
        price: "R$ 600k–800k",
        channels: 384,
        os: "Linux Embedded",
        wifi: true,
        monitorType: "LED 4K",
        monitorSize: 27,
        touchScreen: true,
        storage: "2 TB SSD",
        activePorts: 4,
        usbPorts: 8,
        weight: 90,
        dimensions: "160 x 70 x 100 cm",
        heightAdjust: true,
        articulatedArm: true,
        gelWarmer: true,
        pedalOption: true,
        keyboardType: "Híbrido",
        battery: false,
        transducerHolders: 8,
        radAutoMeas: true,
        radAI: true,
        swConvex: true,
        swLinear: true,
        ceus: true,
        singleCrystal: true,
        maxFreq: 24,
      },
      highlights: ["384 canais", "4K", "Topo de linha"],
      releaseYear: 2024,
    },
    // BARD
    {
      name: "V5",
      shortName: "V5",
      brandName: "BARD",
      tier: "premium",
      tagline: "Equipamento BARD de alta performance",
      description: "Sistema de ultrassom BARD V5 com tecnologia avançada",
      categories: ["Hardware", "Radiologia", "Vascular"],
      bestFor: ["Vascular"],
      differentials: ["Alta resolução", "Conectividade DICOM"],
      specs: {
        price: "R$ 400k–550k",
        channels: 128,
        os: "Windows 10 Embedded",
        wifi: true,
        monitorType: "LED Full HD",
        monitorSize: 21.5,
        touchScreen: true,
        storage: "1 TB SSD",
        activePorts: 4,
        usbPorts: 6,
        weight: 70,
        dimensions: "148 x 58 x 88 cm",
        heightAdjust: true,
        articulatedArm: true,
        gelWarmer: false,
        pedalOption: true,
        keyboardType: "Físico",
        battery: false,
        transducerHolders: 4,
        radAutoMeas: true,
        radAI: false,
        swConvex: true,
        swLinear: true,
        ceus: false,
        singleCrystal: false,
        maxFreq: 15,
      },
      highlights: ["128 canais", "Vascular", "Conectividade DICOM"],
      releaseYear: 2023,
    },
    // BD
    {
      name: "Site-Rite 8",
      shortName: "Site-Rite 8",
      brandName: "BD",
      tier: "medium",
      tagline: "Equipamento BD portátil",
      description: "Sistema de ultrassom BD Site-Rite 8 com portabilidade",
      categories: ["Hardware", "Vascular"],
      bestFor: ["Vascular"],
      differentials: ["Portátil com bateria", "Tela touch"],
      specs: {
        price: "R$ 150k–200k",
        channels: 64,
        os: "Windows 10 IoT",
        wifi: false,
        monitorType: "LED HD",
        monitorSize: 7,
        touchScreen: true,
        storage: "256 GB SSD",
        activePorts: 2,
        usbPorts: 2,
        weight: 1.2,
        dimensions: "20 x 18 x 4 cm",
        heightAdjust: false,
        articulatedArm: false,
        gelWarmer: false,
        pedalOption: false,
        keyboardType: "Virtual",
        battery: true,
        transducerHolders: 1,
        radAutoMeas: false,
        radAI: false,
        swConvex: false,
        swLinear: false,
        ceus: false,
        singleCrystal: false,
        maxFreq: 10,
      },
      highlights: ["Portátil", "Leve", "Vascular"],
      releaseYear: 2022,
    },
    // Fujifilm
    {
      name: "SII",
      shortName: "SII",
      brandName: "Fujifilm",
      tier: "medium",
      tagline: "Equipamento Fujifilm intermediário",
      description: "Sistema de ultrassom Fujifilm SII com bom custo-benefício",
      categories: ["Hardware", "Radiologia"],
      bestFor: ["Radiologia"],
      differentials: ["Conectividade DICOM", "Workflow otimizado"],
      specs: {
        price: "R$ 300k–400k",
        channels: 96,
        os: "Windows 10",
        wifi: true,
        monitorType: "LED Full HD",
        monitorSize: 21.5,
        touchScreen: false,
        storage: "512 GB HDD",
        activePorts: 3,
        usbPorts: 4,
        weight: 68,
        dimensions: "145 x 56 x 86 cm",
        heightAdjust: true,
        articulatedArm: false,
        gelWarmer: false,
        pedalOption: true,
        keyboardType: "Físico",
        battery: false,
        transducerHolders: 4,
        radAutoMeas: true,
        radAI: false,
        swConvex: false,
        swLinear: false,
        ceus: false,
        singleCrystal: false,
        maxFreq: 12,
      },
      highlights: ["Bom custo-benefício", "DICOM", "Workflow"],
      releaseYear: 2022,
    },
    // Esaote
    {
      name: "MyLab X1",
      shortName: "MyLab X1",
      brandName: "Esaote",
      tier: "premium",
      tagline: "Equipamento Esaote premium",
      description: "Sistema de ultrassom Esaote MyLab X1 com tecnologia avançada",
      categories: ["Hardware", "Radiologia", "Cardiologia", "Obstetrícia"],
      bestFor: ["Cardiologia", "Obstetrícia"],
      differentials: ["Alta resolução", "IA integrada", "Suporte 24/7"],
      specs: {
        price: "R$ 520k–680k",
        channels: 192,
        os: "Linux Embedded",
        wifi: true,
        monitorType: "LED 4K",
        monitorSize: 23.8,
        touchScreen: true,
        storage: "1 TB SSD",
        activePorts: 4,
        usbPorts: 6,
        weight: 78,
        dimensions: "150 x 60 x 90 cm",
        heightAdjust: true,
        articulatedArm: true,
        gelWarmer: true,
        pedalOption: true,
        keyboardType: "Híbrido",
        battery: false,
        transducerHolders: 5,
        radAutoMeas: true,
        radAI: true,
        swConvex: true,
        swLinear: true,
        ceus: true,
        singleCrystal: true,
        maxFreq: 18,
      },
      highlights: ["192 canais", "4K", "IA integrada"],
      releaseYear: 2024,
    },
  ],
};
