import { Link, createFileRoute } from "@tanstack/react-router";
import { useMemo, useState } from "react";
import { Copy, ExternalLink, Image, Plus, Save, Search, Trash2, X } from "lucide-react";
import { Icon } from "@/components/Icon";
import { PhotoPicker } from "@/components/PhotoPicker";
import { TierBadge } from "@/components/TierBadge";
import { useStore, tierMeta, type Equipment, type SpecField, type Tier } from "@/lib/store";

export const Route = createFileRoute("/admin/equipments")({ component: EquipmentsAdmin });

const emptyEq = (brandId?: string): Omit<Equipment, "id" | "createdAt"> => ({ name: "Novo equipamento", shortName: "", brandId, tier: "mid", tagline: "", description: "", imageUrl: "", photos: [], categories: [], bestFor: [], differentials: [], specs: {}, highlights: [], releaseYear: new Date().getFullYear() });
const sortByOrder = <T extends { order?: number }>(arr: T[]) => [...arr].sort((a, b) => (a.order ?? 999) - (b.order ?? 999));

function EquipmentsAdmin() {
  const { equipments, brands, fields, addEquipment, updateEquipment, removeEquipment, duplicateEquipment } = useStore();
  const [activeId, setActiveId] = useState<string | null>(equipments[0]?.id ?? null);
  const [q, setQ] = useState("");
  const [brandId, setBrandId] = useState("all");
  const [tier, setTier] = useState<Tier | "all">("all");
  const ownBrand = brands.find((b) => b.isOwn);
  const filtered = useMemo(() => sortByOrder(equipments).filter((e) => (q === "" || e.name.toLowerCase().includes(q.toLowerCase())) && (brandId === "all" || e.brandId === brandId) && (tier === "all" || e.tier === tier)), [equipments, q, brandId, tier]);
  const active = equipments.find((e) => e.id === activeId) ?? filtered[0] ?? null;
  const create = () => { const id = addEquipment(emptyEq(ownBrand?.id)); setActiveId(id); };

  return <div className="min-h-full grid xl:grid-cols-[1fr_520px] bg-background"><section className="px-8 py-8 min-w-0"><div className="flex flex-wrap items-start justify-between gap-4 mb-6"><div><div className="text-[10px] uppercase tracking-widest text-primary font-bold mb-1">Catálogo técnico</div><h1 className="font-display text-3xl font-bold">Equipamentos</h1><p className="text-sm text-muted-foreground mt-1">Cards por modelo. Clique em um equipamento para editar tudo na lateral.</p></div><button onClick={create} className="inline-flex items-center gap-2 rounded-lg bg-primary text-primary-foreground px-4 py-2.5 text-sm font-semibold shadow-glow"><Plus className="h-4 w-4" />Novo equipamento</button></div>
    <div className="glass rounded-2xl p-4 mb-6"><div className="grid lg:grid-cols-[1fr_220px_220px] gap-3"><div className="relative"><Search className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" /><input value={q} onChange={(e) => setQ(e.target.value)} placeholder="Buscar modelo..." className={`${ic} pl-9`} /></div><select value={brandId} onChange={(e) => setBrandId(e.target.value)} className={ic}><option value="all">Todas as marcas</option>{brands.map((b) => <option key={b.id} value={b.id}>{b.name}{b.isOwn ? " ★" : ""}</option>)}</select><select value={tier} onChange={(e) => setTier(e.target.value as Tier | "all")} className={ic}><option value="all">Todos os tiers</option>{Object.entries(tierMeta).map(([k, v]) => <option key={k} value={k}>{v.label}</option>)}</select></div></div>
    <div className="grid md:grid-cols-2 2xl:grid-cols-3 gap-4">{filtered.map((e) => { const brand = brands.find((b) => b.id === e.brandId); const selected = active?.id === e.id; return <button key={e.id} onClick={() => setActiveId(e.id)} className={`text-left rounded-2xl overflow-hidden border bg-card transition hover:-translate-y-0.5 hover:shadow-soft ${selected ? "border-primary shadow-glow" : "border-border"}`}><div className={`h-32 relative ${tierMeta[e.tier].gradient}`}>{e.imageUrl ? <img src={e.imageUrl} alt={e.name} className="h-full w-full object-cover mix-blend-overlay opacity-85" /> : <div className="h-full grid place-items-center text-primary-foreground/70"><Image className="h-9 w-9" /></div>}<div className="absolute top-3 left-3"><TierBadge tier={e.tier} /></div></div><div className="p-4"><div className="text-[10px] uppercase tracking-widest text-muted-foreground font-semibold mb-1">{brand?.name ?? "Sem marca"}</div><div className="font-display font-bold text-lg leading-tight">{e.name}</div><p className="text-sm text-muted-foreground line-clamp-2 mt-1 min-h-[40px]">{e.tagline || e.description || "Sem descrição"}</p><div className="flex items-center gap-2 mt-4 text-xs text-muted-foreground"><span>{Object.keys(e.specs).length} specs</span><span>·</span><span>{e.categories.length} categorias</span></div></div></button>; })}{filtered.length === 0 && <div className="md:col-span-2 2xl:col-span-3 rounded-2xl border border-dashed border-border p-12 text-center text-muted-foreground">Nenhum equipamento encontrado.</div>}</div></section>
    <aside className="xl:sticky xl:top-0 xl:h-screen border-l border-border bg-card/70 backdrop-blur overflow-y-auto scrollbar-thin">{active ? <EquipmentEditor key={active.id} equipment={active} /> : <div className="h-full grid place-items-center p-8 text-center text-muted-foreground">Selecione ou crie um equipamento.</div>}</aside></div>;
}

function EquipmentEditor({ equipment }: { equipment: Equipment }) {
  const { brands, fields, categories, differentials, updateEquipment, removeEquipment, duplicateEquipment, addField, updateField } = useStore();
  const [form, setForm] = useState<Equipment>({ ...equipment, photos: equipment.photos ?? [], highlights: equipment.highlights ?? [] });
  const [newField, setNewField] = useState({ label: "", key: "", type: "boolean" as FieldType, group: "Hardware", unit: "" });
  const save = () => updateEquipment(form.id, form);
  const setSpec = (key: string, value: string | number | boolean | undefined) => { const specs = { ...form.specs }; if (value === undefined || value === "") delete specs[key]; else specs[key] = value; setForm({ ...form, specs }); };
  const toggle = (k: "categories" | "bestFor" | "differentials", id: string) => setForm((f) => ({ ...f, [k]: f[k].includes(id) ? f[k].filter((x) => x !== id) : [...f[k], id] }));
  const addSpecField = () => { if (!newField.label.trim()) return; const key = newField.key.trim() || newField.label.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/[^a-z0-9]+/g, "_").replace(/^_|_$/g, ""); addField({ ...newField, key, unit: newField.unit || undefined, order: fields.length }); setNewField({ label: "", key: "", type: "boolean", group: "Hardware", unit: "" }); };

  return <div><div className="sticky top-0 z-10 bg-card/95 backdrop-blur border-b border-border p-5"><div className="flex items-start gap-3"><div className="h-14 w-14 rounded-xl overflow-hidden bg-muted shrink-0">{form.imageUrl ? <img src={form.imageUrl} alt={form.name} className="h-full w-full object-cover" /> : <div className="h-full grid place-items-center"><Image className="h-5 w-5 text-muted-foreground" /></div>}</div><div className="flex-1 min-w-0"><input value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} className="w-full bg-transparent font-display font-bold text-xl focus:outline-none focus:bg-input/40 rounded px-1 -mx-1" /><div className="mt-1"><TierBadge tier={form.tier} /></div></div></div><div className="grid grid-cols-4 gap-2 mt-4"><button onClick={save} className="col-span-2 inline-flex items-center justify-center gap-2 rounded-lg bg-primary text-primary-foreground px-3 py-2 text-sm font-semibold"><Save className="h-4 w-4" />Salvar</button><button onClick={() => duplicateEquipment(form.id)} className="rounded-lg border border-border hover:bg-accent px-3 py-2 text-sm font-semibold"><Copy className="h-4 w-4 mx-auto" /></button><Link to="/admin/equipments/$equipmentId" params={{ equipmentId: form.id }} className="rounded-lg border border-border hover:bg-accent px-3 py-2 text-sm font-semibold grid place-items-center"><ExternalLink className="h-4 w-4" /></Link></div></div>
    <div className="p-5 space-y-6"><Panel title="Identificação"><div className="grid grid-cols-2 gap-3"><Field label="Marca"><select value={form.brandId ?? ""} onChange={(e) => setForm({ ...form, brandId: e.target.value || undefined })} className={ic}><option value="">Sem marca</option>{brands.map((b) => <option key={b.id} value={b.id}>{b.name}</option>)}</select></Field><Field label="Tier"><select value={form.tier} onChange={(e) => setForm({ ...form, tier: e.target.value as Tier })} className={ic}>{Object.entries(tierMeta).map(([k, v]) => <option key={k} value={k}>{v.label}</option>)}</select></Field><Field label="Apelido"><input value={form.shortName ?? ""} onChange={(e) => setForm({ ...form, shortName: e.target.value })} className={ic} /></Field><Field label="Ano"><input type="number" value={form.releaseYear ?? ""} onChange={(e) => setForm({ ...form, releaseYear: +e.target.value || undefined })} className={ic} /></Field></div><Field label="Tagline"><input value={form.tagline ?? ""} onChange={(e) => setForm({ ...form, tagline: e.target.value })} className={ic} /></Field><Field label="Descrição"><textarea rows={4} value={form.description ?? ""} onChange={(e) => setForm({ ...form, description: e.target.value })} className={ic} /></Field></Panel>
    <Panel title="Imagens"><Field label="Foto principal"><PhotoPicker value={form.imageUrl} onChange={(v) => setForm({ ...form, imageUrl: v ?? "" })} /></Field><div className="grid grid-cols-3 gap-2">{(form.photos ?? []).map((p, i) => <div key={i} className="relative aspect-square rounded-lg overflow-hidden bg-muted"><img src={p} alt="" className="h-full w-full object-cover" /><button onClick={() => setForm({ ...form, photos: (form.photos ?? []).filter((_, j) => j !== i) })} className="absolute top-1 right-1 h-6 w-6 rounded-full bg-card/80 grid place-items-center"><X className="h-3 w-3" /></button></div>)}</div><PhotoPicker value={undefined} onChange={(v) => v && setForm({ ...form, photos: [...(form.photos ?? []), v] })} aspect="square" /></Panel>
    <Panel title="Categorias e diferenciais"><TokenGrid items={categories} selected={form.categories} onToggle={(id) => toggle("categories", id)} /><div className="pt-3 border-t border-border"><div className="text-xs font-semibold mb-2">Melhor para</div><TokenGrid items={categories.filter((c) => form.categories.includes(c.id))} selected={form.bestFor} onToggle={(id) => toggle("bestFor", id)} /></div><div className="pt-3 border-t border-border"><div className="text-xs font-semibold mb-2">Diferenciais</div><TokenGrid items={differentials.map((d) => ({ id: d.id, name: d.label, icon: d.icon }))} selected={form.differentials} onToggle={(id) => toggle("differentials", id)} /></div></Panel>
    <Panel title="Especificações comparativas"><div className="rounded-xl border border-dashed border-border p-3 mb-3"><div className="text-xs font-semibold mb-2">Nova coluna rápida</div><div className="grid grid-cols-2 gap-2"><input value={newField.label} onChange={(e) => setNewField({ ...newField, label: e.target.value })} placeholder="Nome" className={ic} /><select value={newField.type} onChange={(e) => setNewField({ ...newField, type: e.target.value as FieldType })} className={ic}><option value="boolean">Sim/Não</option><option value="text">Texto</option><option value="number">Número</option><option value="select">Lista</option></select><input value={newField.group} onChange={(e) => setNewField({ ...newField, group: e.target.value })} placeholder="Grupo" className={ic} /><button onClick={addSpecField} className="rounded-lg bg-primary text-primary-foreground text-sm font-semibold">Adicionar</button></div></div>{sortByOrder(fields).map((f) => <SpecEditor key={f.id} field={f} value={form.specs[f.key]} onValue={(v) => setSpec(f.key, v)} onField={(p) => updateField(f.id, p)} />)}</Panel>
    <button onClick={() => confirm(`Remover ${form.name}?`) && removeEquipment(form.id)} className="w-full rounded-lg border border-destructive/30 bg-destructive/10 text-destructive py-2 text-sm font-semibold inline-flex items-center justify-center gap-2"><Trash2 className="h-4 w-4" />Remover equipamento</button></div></div>;
}
function SpecEditor({ field, value, onValue, onField }: { field: SpecField; value: string | number | boolean | undefined; onValue: (v: string | number | boolean | undefined) => void; onField: (p: Partial<SpecField>) => void }) { return <div className="rounded-xl border border-border p-3 mb-2"><div className="grid grid-cols-[1fr_110px] gap-2 mb-2"><input value={field.label} onChange={(e) => onField({ label: e.target.value })} className={`${ic} font-semibold`} /><select value={field.type} onChange={(e) => onField({ type: e.target.value as FieldType })} className={ic}><option value="boolean">Sim/Não</option><option value="text">Texto</option><option value="number">Número</option><option value="select">Lista</option></select></div><div className="grid grid-cols-[1fr_1fr] gap-2 mb-2"><input value={field.group ?? ""} onChange={(e) => onField({ group: e.target.value })} className={ic} placeholder="Grupo" /><input value={field.unit ?? ""} onChange={(e) => onField({ unit: e.target.value })} className={ic} placeholder="Unidade" /></div><SpecInput field={field} value={value} onChange={onValue} /></div>; }
function SpecInput({ field, value, onChange }: { field: SpecField; value: string | number | boolean | undefined; onChange: (v: string | number | boolean | undefined) => void }) { if (field.type === "boolean") return <button type="button" onClick={() => onChange(value === true ? false : value === false ? undefined : true)} className={`w-full rounded-lg border px-3 py-2 text-sm font-semibold ${value === true ? "bg-success/15 border-success/40 text-success" : value === false ? "bg-destructive/10 border-destructive/30 text-destructive" : "bg-input/40 border-border text-muted-foreground"}`}>{value === true ? <Check className="h-4 w-4 mx-auto" /> : value === false ? <X className="h-4 w-4 mx-auto" /> : "—"}</button>; return <input type={field.type === "number" ? "number" : "text"} value={value === undefined ? "" : String(value)} onChange={(e) => onChange(field.type === "number" ? (e.target.value === "" ? undefined : +e.target.value) : (e.target.value || undefined))} className={ic} />; }
function TokenGrid({ items, selected, onToggle }: { items: { id: string; name: string; icon: string }[]; selected: string[]; onToggle: (id: string) => void }) { return <div className="flex flex-wrap gap-2">{items.map((item) => <button key={item.id} onClick={() => onToggle(item.id)} className={`inline-flex items-center gap-1.5 rounded-full border px-3 py-1.5 text-xs font-semibold ${selected.includes(item.id) ? "bg-primary/15 border-primary" : "border-border text-muted-foreground hover:text-foreground"}`}><Icon name={item.icon} className="h-3.5 w-3.5" />{item.name}</button>)}</div>; }
function Panel({ title, children }: { title: string; children: React.ReactNode }) { return <section className="space-y-3"><h2 className="font-display text-lg font-bold">{title}</h2>{children}</section>; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block"><span className="block text-[11px] font-semibold text-muted-foreground mb-1.5">{label}</span>{children}</label>; }
const ic = "w-full bg-input/40 border border-border rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-primary/40 focus:border-primary";
