import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import { Plus, Trash2 } from "lucide-react";
import { Icon } from "@/components/Icon";
import { useStore } from "@/lib/store";
export const Route = createFileRoute("/admin/differentials")({ component: DifferentialsAdmin });
const presets=["Crystal Architecture™","S-Vue™ Transducers","BiometryAssist™","HeartAssist™","Workflow rápido","DICOM","Portátil com bateria"];
function DifferentialsAdmin(){const{differentials,addDifferential,updateDifferential,removeDifferential}=useStore();const[d,setD]=useState({label:"",icon:"Zap"});const submit=()=>{if(!d.label.trim())return;addDifferential({...d,order:differentials.length});setD({label:"",icon:"Zap"})};return <div className="px-8 py-8 max-w-6xl"><div className="mb-8"><div className="text-[10px] uppercase tracking-widest text-primary font-bold mb-1">Vantagens</div><h1 className="font-display text-3xl font-bold">Diferenciais</h1><p className="text-sm text-muted-foreground mt-1">Crie selos técnicos reutilizáveis nos equipamentos e comparações.</p></div><section className="glass rounded-2xl p-5 mb-8"><div className="grid md:grid-cols-[1fr_180px_140px] gap-3"><input value={d.label} onChange={(e)=>setD({...d,label:e.target.value})} placeholder="Diferencial" className={ic}/><input value={d.icon} onChange={(e)=>setD({...d,icon:e.target.value})} placeholder="Ícone" className={ic}/><button onClick={submit} className="rounded-lg bg-primary text-primary-foreground text-sm font-semibold inline-flex items-center justify-center gap-2"><Plus className="h-4 w-4"/>Adicionar</button></div><div className="flex flex-wrap gap-2 mt-3">{presets.map((p)=><button key={p} onClick={()=>setD({...d,label:p})} className="rounded-full border border-border px-3 py-1 text-xs font-semibold text-muted-foreground hover:text-foreground">{p}</button>)}</div></section><div className="grid md:grid-cols-2 gap-3">{differentials.map((diff)=><div key={diff.id} className="rounded-2xl border border-border bg-card p-4 flex items-center gap-3 shadow-soft"><div className="h-10 w-10 rounded-xl bg-primary/10 text-primary grid place-items-center"><Icon name={diff.icon} className="h-4 w-4"/></div><input value={diff.label} onChange={(e)=>updateDifferential(diff.id,{label:e.target.value})} className={`${ic} flex-1 font-semibold`}/><input value={diff.icon} onChange={(e)=>updateDifferential(diff.id,{icon:e.target.value})} className={`${ic} w-32`}/><button onClick={()=>confirm("Remover diferencial?")&&removeDifferential(diff.id)} className="h-9 w-9 rounded-lg grid place-items-center text-muted-foreground hover:text-destructive hover:bg-destructive/10"><Trash2 className="h-4 w-4"/></button></div>)}</div></div>}
const ic="w-full bg-input/40 border border-border rounded-lg px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-primary/40";
